# Generated by Django 2.0.5 on 2018-05-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='abou_test',
        ),
    ]
