# Generated by Django 2.0.5 on 2018-05-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180525_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='mail',
            field=models.EmailField(default=0, max_length=20, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='commets',
            name='name',
            field=models.CharField(default=0, max_length=20, verbose_name='别名'),
        ),
    ]
