# Generated by Django 2.0.6 on 2018-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.CharField(default='', max_length=120, verbose_name='课程详情'),
        ),
    ]
