# Generated by Django 2.0.5 on 2018-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_text', models.TextField()),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=20, verbose_name='博客标题')),
                ('times', models.DateTimeField(default=None, verbose_name='时间')),
                ('author', models.CharField(max_length=20, verbose_name='发布者')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('reads', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('text', models.TextField(verbose_name='发表内容')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-times'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('People_id', models.CharField(default=False, max_length=20, verbose_name='评论ID')),
                ('advice', models.TextField(default=False, verbose_name='评论建议')),
                ('mail', models.EmailField(default=False, max_length=254, verbose_name='邮箱')),
                ('link', models.CharField(default=False, max_length=50, verbose_name='友链')),
                ('time', models.DateTimeField(default=None, verbose_name='评论时间')),
            ],
        ),
    ]
