# Generated by Django 2.0.5 on 2018-05-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='aAbout',
        ),
    ]
