# Generated by Django 2.0.5 on 2018-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_auto_20180515_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='aComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('People_id', models.CharField(default=False, max_length=20, verbose_name='评论ID')),
                ('advice', models.TextField(default=False, verbose_name='评论建议')),
                ('mail', models.EmailField(default=False, max_length=254, verbose_name='邮箱')),
                ('link', models.CharField(default=False, max_length=50, verbose_name='友链')),
                ('time', models.DateTimeField(default=None, verbose_name='评论时间')),
            ],
        ),
        migrations.DeleteModel(
            name='aAbout',
        ),
    ]
