# Generated by Django 2.0.5 on 2018-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_auto_20180515_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per_Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_texts', models.TextField()),
                ('times', models.DateTimeField(default=0, verbose_name='时间')),
            ],
            options={
                'verbose_name': '每日一句',
                'verbose_name_plural': '每日一句',
            },
        ),
        migrations.DeleteModel(
            name='aComment',
        ),
    ]
