# Generated by Django 2.0.6 on 2018-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('培训机构', '培训机构'), ('高校', '高校'), ('个人', '个人')], default='pxjg', max_length=20, verbose_name='机构类别'),
        ),
    ]
