# Generated by Django 2.0.6 on 2018-06-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180618_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='hop_price',
            new_name='shop_price',
        ),
    ]
